//! RS Shuffle Constraint Count and Spartan Proof Example
//!
//! This example measures the number of R1CS constraints generated by the RS shuffle circuit
//! and optionally generates a Spartan proof.
//!
//! Run with:
//!   cargo run --release --example rs_shuffle_constraints -- count      # Just count constraints
//!   cargo run --release --example rs_shuffle_constraints -- spartan    # Non-ZK Spartan proof
//!   cargo run --release --example rs_shuffle_constraints -- spartan-zk # ZK Spartan proof

use ark_bn254::Fr as BaseField;
use ark_ec::{CurveConfig, PrimeGroup};
use ark_ff::UniformRand;
use ark_grumpkin::{GrumpkinConfig, Projective as GrumpkinProjective};
use ark_r1cs_std::alloc::AllocVar;
use ark_r1cs_std::fields::fp::FpVar;
use ark_r1cs_std::groups::curves::short_weierstrass::ProjectiveVar;
use ark_r1cs_std::prelude::AllocationMode;
use ark_relations::r1cs::{ConstraintSynthesizer, ConstraintSystem, ConstraintSystemRef};
use clap::{Parser, Subcommand};
use halo2curves::bn256::Fr as Bn256Fr;

use spartan2::rs_shuffle::bit_generation::derive_split_bits;
use spartan2::rs_shuffle::data_structures::{
    ElGamalCiphertext, ElGamalCiphertextVar, PermutationWitnessTrace, PermutationWitnessTraceVar,
};
use spartan2::rs_shuffle::encryption::ElGamalEncryption;
use spartan2::rs_shuffle::gadget::{rs_shuffle, rs_shuffle_with_reencryption};
use spartan2::rs_shuffle::native::run_rs_shuffle_permutation;

type GrumpkinVar = ProjectiveVar<GrumpkinConfig, FpVar<BaseField>>;

/// Standard deck size
const N: usize = 52;
/// Number of shuffle levels (log2(52) rounded up)
const LEVELS: usize = 6;

/// RS Shuffle circuit that implements ConstraintSynthesizer.
/// This allows us to use `extract_witness_only` for fast witness generation.
#[derive(Clone)]
struct RsShuffleCircuit {
    /// Seed for the shuffle (public input)
    seed: BaseField,
    /// Input ciphertexts (public input)
    ct_input: [ElGamalCiphertext<GrumpkinProjective>; N],
    /// Shuffled ciphertexts before re-encryption (witness)
    ct_shuffled: [ElGamalCiphertext<GrumpkinProjective>; N],
    /// Output ciphertexts after re-encryption (public input)
    ct_output: [ElGamalCiphertext<GrumpkinProjective>; N],
    /// Public key for re-encryption (public input)
    pk: GrumpkinProjective,
    /// Permutation witness trace
    witness_trace: PermutationWitnessTrace<N, LEVELS>,
    /// Re-randomization values for re-encryption
    rerandomizations: [BaseField; N],
    /// Challenge alpha (public input)
    alpha: BaseField,
    /// Challenge beta (public input)
    beta: BaseField,
    /// Precomputed generator powers for efficient scalar multiplication
    generator_powers: Vec<GrumpkinProjective>,
    /// Number of Poseidon samples needed
    num_samples: usize,
}

impl RsShuffleCircuit {
    fn new(
        seed: BaseField,
        ct_input: [ElGamalCiphertext<GrumpkinProjective>; N],
        ct_shuffled: [ElGamalCiphertext<GrumpkinProjective>; N],
        ct_output: [ElGamalCiphertext<GrumpkinProjective>; N],
        pk: GrumpkinProjective,
        witness_trace: PermutationWitnessTrace<N, LEVELS>,
        rerandomizations: [BaseField; N],
        alpha: BaseField,
        beta: BaseField,
        generator_powers: Vec<GrumpkinProjective>,
        num_samples: usize,
    ) -> Self {
        Self {
            seed,
            ct_input,
            ct_shuffled,
            ct_output,
            pk,
            witness_trace,
            rerandomizations,
            alpha,
            beta,
            generator_powers,
            num_samples,
        }
    }
}

impl ConstraintSynthesizer<BaseField> for RsShuffleCircuit {
    fn generate_constraints(
        self,
        cs: ConstraintSystemRef<BaseField>,
    ) -> Result<(), ark_relations::r1cs::SynthesisError> {
        // Allocate seed
        let seed_var =
            FpVar::new_input(cs.clone(), || Ok(self.seed)).expect("Failed to allocate seed");

        // Allocate input ciphertexts
        let ct_input_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
            std::array::from_fn(|i| {
                ElGamalCiphertextVar::new_variable(
                    cs.clone(),
                    || Ok(&self.ct_input[i]),
                    AllocationMode::Input,
                )
                .expect("Failed to allocate input ciphertext")
            });

        // Allocate shuffled ciphertexts (intermediate - witness)
        let ct_shuffled_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
            std::array::from_fn(|i| {
                ElGamalCiphertextVar::new_variable(
                    cs.clone(),
                    || Ok(&self.ct_shuffled[i]),
                    AllocationMode::Witness,
                )
                .expect("Failed to allocate shuffled ciphertext")
            });

        // Allocate output ciphertexts
        let ct_output_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
            std::array::from_fn(|i| {
                ElGamalCiphertextVar::new_variable(
                    cs.clone(),
                    || Ok(&self.ct_output[i]),
                    AllocationMode::Input,
                )
                .expect("Failed to allocate output ciphertext")
            });

        // Allocate public key
        let pk_var =
            GrumpkinVar::new_variable(cs.clone(), || Ok(self.pk), AllocationMode::Input)
                .expect("Failed to allocate public key");

        // Allocate challenges
        let alpha_var = FpVar::new_input(cs.clone(), || Ok(self.alpha))
            .expect("Failed to allocate alpha");
        let beta_var =
            FpVar::new_input(cs.clone(), || Ok(self.beta)).expect("Failed to allocate beta");

        // Allocate witness
        let witness_var = PermutationWitnessTraceVar::new_variable(
            cs.clone(),
            || Ok(&self.witness_trace),
            AllocationMode::Witness,
        )
        .expect("Failed to allocate witness");

        // Allocate rerandomizations
        let rerand_vars: [FpVar<BaseField>; N] = std::array::from_fn(|i| {
            FpVar::new_witness(cs.clone(), || Ok(self.rerandomizations[i]))
                .expect("Failed to allocate rerandomization")
        });

        // Run the full verification
        rs_shuffle_with_reencryption::<GrumpkinProjective, GrumpkinVar, N, LEVELS>(
            cs,
            &seed_var,
            &ct_input_vars,
            &ct_shuffled_vars,
            &ct_output_vars,
            &pk_var,
            &alpha_var,
            &beta_var,
            &witness_var,
            &rerand_vars,
            self.num_samples,
            &self.generator_powers,
        )
        .expect("rs_shuffle_with_reencryption failed");

        Ok(())
    }
}

#[derive(Parser)]
#[command(name = "rs_shuffle_constraints")]
#[command(about = "RS Shuffle constraint counting and Spartan proof generation")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Just count constraints (no proof generation)
    Count,
    /// Generate non-ZK Spartan proof
    Spartan,
    /// Generate ZK Spartan proof
    SpartanZk,
}

fn main() {
    // Initialize tracing for timing breakdown
    use tracing_subscriber::EnvFilter;
    let _ = tracing_subscriber::fmt()
        .with_target(false)
        .with_env_filter(EnvFilter::from_default_env())
        .try_init();

    let cli = Cli::parse();

    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║         RS Shuffle Circuit Constraint Counter                ║");
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  N = {} cards, LEVELS = {}                                   ║",
        N, LEVELS
    );
    println!("╚══════════════════════════════════════════════════════════════╝\n");

    let mut rng = ark_std::test_rng();

    // Generate keys
    let sk = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
    let pk = GrumpkinProjective::generator() * sk;

    // Create initial ciphertexts (encrypted cards)
    println!("Creating {} encrypted cards...", N);
    let ct_init: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let message = <GrumpkinConfig as CurveConfig>::ScalarField::from(i as u64);
        let randomness = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
        ElGamalCiphertext::encrypt_scalar(message, randomness, pk)
    });

    // Run native shuffle to generate witness
    println!("Running native RS shuffle...");
    let seed = BaseField::from(42u64);
    let rs_trace = run_rs_shuffle_permutation::<BaseField, _, N, LEVELS>(seed, &ct_init);

    // =========================================================================
    // Measure constraints for shuffle-only (without re-encryption)
    // =========================================================================
    println!("\n--- Shuffle Only (no re-encryption) ---");

    let cs_shuffle = ConstraintSystem::<BaseField>::new_ref();

    // Allocate circuit variables
    let ct_init_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_shuffle.clone(),
                || Ok(&ct_init[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate initial ciphertext")
        });

    let ct_shuffled_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_shuffle.clone(),
                || Ok(&rs_trace.permuted_output[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate shuffled ciphertext")
        });

    let witness_var = PermutationWitnessTraceVar::new_variable(
        cs_shuffle.clone(),
        || Ok(&rs_trace.witness_trace),
        AllocationMode::Witness,
    )
    .expect("Failed to allocate witness");

    let alpha = FpVar::new_input(cs_shuffle.clone(), || Ok(BaseField::from(17u64)))
        .expect("Failed to allocate alpha");
    let beta = FpVar::new_input(cs_shuffle.clone(), || Ok(BaseField::from(23u64)))
        .expect("Failed to allocate beta");

    let constraints_before = cs_shuffle.num_constraints();

    // Run the shuffle verification
    rs_shuffle::<GrumpkinProjective, GrumpkinVar, N, LEVELS>(
        cs_shuffle.clone(),
        &ct_init_vars,
        &ct_shuffled_vars,
        &witness_var,
        &alpha,
        &beta,
    )
    .expect("rs_shuffle failed");

    let constraints_after = cs_shuffle.num_constraints();
    let shuffle_constraints = constraints_after - constraints_before;

    println!("  Constraints before shuffle: {}", constraints_before);
    println!("  Constraints after shuffle:  {}", constraints_after);
    println!("  Shuffle-only constraints:   {}", shuffle_constraints);
    println!(
        "  Constraint system satisfied: {}",
        cs_shuffle.is_satisfied().unwrap()
    );

    // =========================================================================
    // Measure constraints for full circuit (with re-encryption)
    // =========================================================================
    println!("\n--- Full Circuit (with re-encryption) ---");

    let cs_full = ConstraintSystem::<BaseField>::new_ref();

    // Allocate seed
    let seed_var =
        FpVar::new_input(cs_full.clone(), || Ok(seed)).expect("Failed to allocate seed");

    // Allocate input ciphertexts
    let ct_input_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&ct_init[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate input ciphertext")
        });

    // Allocate shuffled ciphertexts (intermediate)
    let ct_shuffled_full: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&rs_trace.permuted_output[i]),
                AllocationMode::Witness,
            )
            .expect("Failed to allocate shuffled ciphertext")
        });

    // Generate re-encryption randomizations
    use ark_ff::{BigInteger, PrimeField};
    let rerandomizations: [BaseField; N] = std::array::from_fn(|_| BaseField::rand(&mut rng));

    // Compute re-encrypted output natively
    let ct_output: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let r_scalar = <GrumpkinConfig as CurveConfig>::ScalarField::from_le_bytes_mod_order(
            &rerandomizations[i].into_bigint().to_bytes_le(),
        );
        rs_trace.permuted_output[i].add_encryption_layer(r_scalar, &pk)
    });

    // Allocate output ciphertexts
    let ct_output_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&ct_output[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate output ciphertext")
        });

    // Allocate public key
    let pk_var = GrumpkinVar::new_variable(cs_full.clone(), || Ok(pk), AllocationMode::Input)
        .expect("Failed to allocate public key");

    // Allocate challenges
    let alpha_full = FpVar::new_input(cs_full.clone(), || Ok(BaseField::from(17u64)))
        .expect("Failed to allocate alpha");
    let beta_full = FpVar::new_input(cs_full.clone(), || Ok(BaseField::from(23u64)))
        .expect("Failed to allocate beta");

    // Allocate witness
    let witness_full = PermutationWitnessTraceVar::new_variable(
        cs_full.clone(),
        || Ok(&rs_trace.witness_trace),
        AllocationMode::Witness,
    )
    .expect("Failed to allocate witness");

    // Allocate rerandomizations
    let rerand_vars: [FpVar<BaseField>; N] = std::array::from_fn(|i| {
        FpVar::new_witness(cs_full.clone(), || Ok(rerandomizations[i]))
            .expect("Failed to allocate rerandomization")
    });

    // Precompute generator powers
    let generator_powers = ElGamalEncryption::<GrumpkinProjective>::precompute_generator_powers();

    // Get number of Poseidon samples needed
    let (_, num_samples) = derive_split_bits::<BaseField, N, LEVELS>(seed);

    let constraints_before_full = cs_full.num_constraints();

    // Run the full verification
    rs_shuffle_with_reencryption::<GrumpkinProjective, GrumpkinVar, N, LEVELS>(
        cs_full.clone(),
        &seed_var,
        &ct_input_vars,
        &ct_shuffled_full,
        &ct_output_vars,
        &pk_var,
        &alpha_full,
        &beta_full,
        &witness_full,
        &rerand_vars,
        num_samples,
        &generator_powers,
    )
    .expect("rs_shuffle_with_reencryption failed");

    let constraints_after_full = cs_full.num_constraints();
    let full_constraints = constraints_after_full - constraints_before_full;

    println!("  Constraints before circuit: {}", constraints_before_full);
    println!("  Constraints after circuit:  {}", constraints_after_full);
    println!("  Full circuit constraints:   {}", full_constraints);
    println!(
        "  Constraint system satisfied: {}",
        cs_full.is_satisfied().unwrap()
    );

    // =========================================================================
    // Summary
    // =========================================================================
    println!("\n╔══════════════════════════════════════════════════════════════╗");
    println!("║                        SUMMARY                               ║");
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  Shuffle-only constraints:     {:>10}                   ║",
        shuffle_constraints
    );
    println!(
        "║  Full circuit constraints:     {:>10}                   ║",
        full_constraints
    );
    println!(
        "║  Re-encryption overhead:       {:>10}                   ║",
        full_constraints.saturating_sub(shuffle_constraints)
    );
    println!(
        "║  Constraints per card:         {:>10.1}                   ║",
        full_constraints as f64 / N as f64
    );
    println!("╚══════════════════════════════════════════════════════════════╝");

    // =========================================================================
    // Spartan Proof Generation (if requested)
    // =========================================================================
    match cli.command {
        Commands::Count => {
            println!("\n(Skipping proof generation - use 'spartan' or 'spartan-zk' subcommand)");
        }
        Commands::Spartan => {
            run_spartan_proof(&cs_full, constraints_after_full);
        }
        Commands::SpartanZk => {
            run_spartan_zk_proof(&cs_full, constraints_after_full);
        }
    }
}

fn run_spartan_proof(
    cs_full: &ark_relations::r1cs::ConstraintSystemRef<BaseField>,
    total_constraints: usize,
) {
    use spartan2::arkworks::{
        convert_constraint_matrices, extract_assignments, ArkworksCircuitAdapter,
    };
    use spartan2::provider::Bn254Engine;
    use spartan2::spartan::SpartanSNARK;
    use spartan2::traits::snark::R1CSSNARKTrait;
    use std::time::Instant;

    println!("\n--- Spartan (non-ZK) Proof ---");

    // Finalize the constraint system
    cs_full.finalize();

    // Extract matrices and assignments
    println!("  Extracting matrices and assignments...");
    let matrices = cs_full.to_matrices().expect("Failed to get matrices");
    let (a, b, c) = convert_constraint_matrices::<BaseField, Bn256Fr>(&matrices);
    let (w, x) = extract_assignments::<BaseField, Bn256Fr>(cs_full);

    println!(
        "  Matrices: {} constraints, {} witness vars, {} public inputs",
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1
    );

    // Create adapter
    let adapter = ArkworksCircuitAdapter::new(
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1,
        a,
        b,
        c,
        w,
        x,
    );

    // Setup
    println!("  Running Spartan setup...");
    let setup_start = Instant::now();
    let (pk, vk) = SpartanSNARK::<Bn254Engine>::setup(adapter.clone()).expect("Setup failed");
    let setup_time = setup_start.elapsed();
    println!("  Setup time: {:?}", setup_time);

    // Prep prove
    println!("  Running prep_prove...");
    let prep_start = Instant::now();
    let prep = SpartanSNARK::<Bn254Engine>::prep_prove(&pk, adapter.clone(), false)
        .expect("Prep prove failed");
    let prep_time = prep_start.elapsed();
    println!("  Prep time: {:?}", prep_time);

    // Prove
    println!("  Generating proof...");
    let prove_start = Instant::now();
    let snark = SpartanSNARK::<Bn254Engine>::prove(&pk, adapter, &prep, false)
        .expect("Proof generation failed");
    let prove_time = prove_start.elapsed();
    println!("  Prove time: {:?}", prove_time);

    // Verify
    println!("  Verifying proof...");
    let verify_start = Instant::now();
    let result = snark.verify(&vk);
    let verify_time = verify_start.elapsed();

    match result {
        Ok(public_outputs) => {
            println!("  ✓ Proof verified successfully!");
            println!("  Verify time: {:?}", verify_time);
            println!("  Public outputs: {} values", public_outputs.len());
        }
        Err(e) => {
            println!("  ✗ Verification failed: {:?}", e);
        }
    }

    print_spartan_summary(
        "SPARTAN (non-ZK)",
        setup_time,
        prep_time + prove_time,
        verify_time,
        total_constraints,
    );
}

fn run_spartan_zk_proof(
    _cs_full: &ark_relations::r1cs::ConstraintSystemRef<BaseField>,
    total_constraints: usize,
) {
    use ark_ff::{BigInteger, PrimeField};
    use spartan2::arkworks::{
        convert_constraint_matrices, extract_assignments, extract_witness_only,
        ArkworksCircuitAdapter,
    };
    use spartan2::provider::Bn254Engine;
    use spartan2::spartan_zk::SpartanZkSNARK;
    use spartan2::timing::{TimingLayer, SPARTAN_ZK_PHASES, clear_timings, snapshot_timings};
    use spartan2::traits::snark::R1CSSNARKTrait;
    use std::time::Instant;
    use tracing_subscriber::prelude::*;

    println!("\n--- Spartan zkSNARK Proof (Correct Flow) ---");
    println!("  Matrices extracted at SETUP, witnesses computed at PROVE time\n");

    // Setup tracing with TimingLayer to capture phase timings
    let (timing_layer, timing_data, _constraints) = TimingLayer::new();
    let subscriber = tracing_subscriber::registry().with(timing_layer);
    let _guard = tracing::subscriber::set_default(subscriber);

    let mut rng = ark_std::test_rng();

    // Generate keys
    let sk = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
    let pk = GrumpkinProjective::generator() * sk;

    // Precompute generator powers (shared across all proofs)
    let generator_powers = ElGamalEncryption::<GrumpkinProjective>::precompute_generator_powers();

    // ========================================================================
    // SETUP PHASE: Extract matrices (done ONCE)
    // ========================================================================
    println!("  === SETUP PHASE (extract matrices once) ===");

    // Create initial cards for setup
    let ct_init_setup: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let message = <GrumpkinConfig as CurveConfig>::ScalarField::from(i as u64);
        let randomness = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
        ElGamalCiphertext::encrypt_scalar(message, randomness, pk)
    });

    // Run native shuffle for setup witness
    let seed_setup = BaseField::from(42u64);
    let rs_trace_setup =
        run_rs_shuffle_permutation::<BaseField, _, N, LEVELS>(seed_setup, &ct_init_setup);

    // Generate re-encryption data for setup
    let rerandomizations_setup: [BaseField; N] =
        std::array::from_fn(|_| BaseField::rand(&mut rng));
    let ct_output_setup: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let r_scalar = <GrumpkinConfig as CurveConfig>::ScalarField::from_le_bytes_mod_order(
            &rerandomizations_setup[i].into_bigint().to_bytes_le(),
        );
        rs_trace_setup.permuted_output[i].add_encryption_layer(r_scalar, &pk)
    });

    let (_, num_samples) = derive_split_bits::<BaseField, N, LEVELS>(seed_setup);

    // Create circuit for setup
    let circuit_setup = RsShuffleCircuit::new(
        seed_setup,
        ct_init_setup.clone(),
        rs_trace_setup.permuted_output.clone(),
        ct_output_setup,
        pk,
        rs_trace_setup.witness_trace.clone(),
        rerandomizations_setup,
        BaseField::from(17u64),
        BaseField::from(23u64),
        generator_powers.clone(),
        num_samples,
    );

    // Extract matrices (full synthesis)
    println!("  Synthesizing circuit to extract matrices...");
    let setup_synth_start = Instant::now();
    let cs_setup = ConstraintSystem::<BaseField>::new_ref();
    circuit_setup
        .clone()
        .generate_constraints(cs_setup.clone())
        .expect("Setup synthesis failed");
    cs_setup.finalize();
    let setup_synth_time = setup_synth_start.elapsed();
    println!("  Full synthesis time: {:?}", setup_synth_time);

    let matrices = cs_setup.to_matrices().expect("Failed to get matrices");
    let (a, b, c) = convert_constraint_matrices::<BaseField, Bn256Fr>(&matrices);
    let (w_setup, x_setup) = extract_assignments::<BaseField, Bn256Fr>(&cs_setup);

    println!(
        "  Matrices: {} constraints, {} witness vars, {} public inputs",
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1
    );

    // Create adapter with setup witness (will be replaced at prove time)
    let mut adapter = ArkworksCircuitAdapter::new(
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1,
        a,
        b,
        c,
        w_setup,
        x_setup,
    );

    // Spartan setup
    println!("  Running Spartan setup...");
    let setup_start = Instant::now();
    let (prover_key, vk) =
        SpartanZkSNARK::<Bn254Engine>::setup(adapter.clone()).expect("Setup failed");
    let setup_time = setup_start.elapsed();
    println!("  Spartan setup time: {:?}", setup_time);

    // ========================================================================
    // PROVE PHASE: Generate witness with NEW inputs (done for EACH proof)
    // ========================================================================
    println!("\n  === PROVE PHASE (compute witness at prove time) ===");

    // Create NEW cards with DIFFERENT randomness (simulating a new shuffle)
    let ct_init_prove: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let message = <GrumpkinConfig as CurveConfig>::ScalarField::from(i as u64);
        let randomness = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
        ElGamalCiphertext::encrypt_scalar(message, randomness, pk)
    });

    // Use a DIFFERENT seed
    let seed_prove = BaseField::from(999u64);

    // Run native shuffle with new inputs
    println!("  Running native shuffle with NEW inputs...");
    let native_start = Instant::now();
    let rs_trace_prove =
        run_rs_shuffle_permutation::<BaseField, _, N, LEVELS>(seed_prove, &ct_init_prove);
    let native_time = native_start.elapsed();
    println!("  Native shuffle time: {:?}", native_time);

    // Generate re-encryption data
    let rerandomizations_prove: [BaseField; N] =
        std::array::from_fn(|_| BaseField::rand(&mut rng));
    let ct_output_prove: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let r_scalar = <GrumpkinConfig as CurveConfig>::ScalarField::from_le_bytes_mod_order(
            &rerandomizations_prove[i].into_bigint().to_bytes_le(),
        );
        rs_trace_prove.permuted_output[i].add_encryption_layer(r_scalar, &pk)
    });

    let (_, num_samples_prove) = derive_split_bits::<BaseField, N, LEVELS>(seed_prove);

    // Create circuit with NEW inputs
    let circuit_prove = RsShuffleCircuit::new(
        seed_prove,
        ct_init_prove,
        rs_trace_prove.permuted_output,
        ct_output_prove,
        pk,
        rs_trace_prove.witness_trace,
        rerandomizations_prove,
        BaseField::from(17u64),
        BaseField::from(23u64),
        generator_powers,
        num_samples_prove,
    );

    // Extract witness ONLY (fast - no matrix construction!)
    println!("  Extracting witness only (no matrix construction)...");
    let witness_start = Instant::now();
    let (w_prove, x_prove) =
        extract_witness_only::<BaseField, Bn256Fr, _>(circuit_prove).expect("Witness extraction failed");
    let witness_time = witness_start.elapsed();
    println!("  >>> Witness extraction time: {:?} <<<", witness_time);

    // Update adapter with fresh witness
    adapter.update_witness(w_prove, x_prove);

    // Prep prove
    println!("  Running prep_prove...");
    clear_timings(&timing_data);
    let prep_start = Instant::now();
    let prep = SpartanZkSNARK::<Bn254Engine>::prep_prove(&prover_key, adapter.clone(), false)
        .expect("Prep prove failed");
    let prep_time = prep_start.elapsed();
    let prep_timings = snapshot_timings(&timing_data, SPARTAN_ZK_PHASES);
    println!("  Prep time: {:?}", prep_time);

    // Prove
    println!("  Generating proof...");
    clear_timings(&timing_data);
    let prove_start = Instant::now();
    let snark = SpartanZkSNARK::<Bn254Engine>::prove(&prover_key, adapter, &prep, false)
        .expect("Proof generation failed");
    let prove_time = prove_start.elapsed();
    let prove_timings = snapshot_timings(&timing_data, SPARTAN_ZK_PHASES);
    println!("  Prove time: {:?}", prove_time);

    // Verify
    println!("  Verifying proof...");
    let verify_start = Instant::now();
    let result = snark.verify(&vk);
    let verify_time = verify_start.elapsed();

    match result {
        Ok(public_outputs) => {
            println!("  ✓ Proof verified successfully!");
            println!("  Verify time: {:?}", verify_time);
            println!("  Public outputs: {} values", public_outputs.len());
        }
        Err(e) => {
            println!("  ✗ Verification failed: {:?}", e);
        }
    }

    // Summary with detailed timing breakdown
    print_zk_timing_breakdown(
        setup_synth_time,
        setup_time,
        native_time,
        witness_time,
        prep_time,
        prove_time,
        verify_time,
        &prep_timings,
        &prove_timings,
        total_constraints,
    );
}

fn print_zk_timing_breakdown(
    setup_synth_time: std::time::Duration,
    setup_time: std::time::Duration,
    native_time: std::time::Duration,
    witness_time: std::time::Duration,
    prep_time: std::time::Duration,
    prove_time: std::time::Duration,
    verify_time: std::time::Duration,
    _prep_timings: &std::collections::HashMap<&str, u64>,
    prove_timings: &std::collections::HashMap<&str, u64>,
    total_constraints: usize,
) {
    // Helper to print a phase if it has non-zero timing
    let print_phase = |name: &str, key: &str| {
        let ms = prove_timings.get(key).copied().unwrap_or(0);
        if ms > 0 {
            println!(
                "║      └─ {:<24}{:>8}ms                        ║",
                format!("{}:", name),
                ms
            );
        }
    };

    println!("\n╔══════════════════════════════════════════════════════════════════════════╗");
    println!("║                   SPARTAN zkSNARK TIMING BREAKDOWN                       ║");
    println!("╠══════════════════════════════════════════════════════════════════════════╣");
    println!("║  SETUP (done once):                                                      ║");
    println!(
        "║    Full synthesis (Arkworks):     {:>12.2?}                         ║",
        setup_synth_time
    );
    println!(
        "║    Spartan setup (keys, VC):      {:>12.2?}                         ║",
        setup_time
    );
    println!(
        "║    ─────────────────────────────────────────────                            ║"
    );
    println!(
        "║    TOTAL SETUP:                   {:>12.2?}                         ║",
        setup_synth_time + setup_time
    );
    println!("╠══════════════════════════════════════════════════════════════════════════╣");
    println!("║  PROVE (per proof):                                                      ║");
    println!(
        "║    Native RS shuffle:            {:>12.2?}                         ║",
        native_time
    );
    println!(
        "║    Witness extraction:           {:>12.2?}                         ║",
        witness_time
    );
    println!(
        "║    Prep:                         {:>12.2?}                         ║",
        prep_time
    );
    println!(
        "║    ─────────────────────────────────────────────                            ║"
    );
    println!(
        "║    Prove:                        {:>12.2?}                         ║",
        prove_time
    );
    print_phase("r1cs_instance_witness", "r1cs_inst");
    print_phase("matrix_vector_multiply", "mat_vec");
    print_phase("outer_sumcheck", "outer_sc");
    print_phase("inner_sumcheck", "inner_sc");
    print_phase("finalize_and_nifs", "nifs");
    print_phase("pcs_prove", "pcs");
    println!(
        "║    ─────────────────────────────────────────────                            ║"
    );
    println!(
        "║    TOTAL PROVE (excl native):    {:>12.2?}                         ║",
        witness_time + prep_time + prove_time
    );
    println!("╠══════════════════════════════════════════════════════════════════════════╣");
    println!(
        "║  VERIFY:                         {:>12.2?}                         ║",
        verify_time
    );
    println!("╠══════════════════════════════════════════════════════════════════════════╣");
    println!(
        "║  Total constraints:              {:>12}                         ║",
        total_constraints
    );
    println!("╚══════════════════════════════════════════════════════════════════════════╝");
}

fn print_spartan_summary(
    name: &str,
    setup_time: std::time::Duration,
    prove_time: std::time::Duration,
    verify_time: std::time::Duration,
    total_constraints: usize,
) {
    println!("\n╔══════════════════════════════════════════════════════════════╗");
    println!(
        "║              {} PROOF SUMMARY                 ║",
        name
    );
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  Setup time:                   {:>10.2?}                 ║",
        setup_time
    );
    println!(
        "║  Prove time:                   {:>10.2?}                 ║",
        prove_time
    );
    println!(
        "║  Verify time:                  {:>10.2?}                 ║",
        verify_time
    );
    println!(
        "║  Total constraints:            {:>10}                   ║",
        total_constraints
    );
    println!("╚══════════════════════════════════════════════════════════════╝");
}
