//! RS Shuffle Constraint Count and Spartan Proof Example
//!
//! This example measures the number of R1CS constraints generated by the RS shuffle circuit
//! and optionally generates a Spartan proof.
//!
//! Run with:
//!   cargo run --release --example rs_shuffle_constraints -- count      # Just count constraints
//!   cargo run --release --example rs_shuffle_constraints -- spartan    # Non-ZK Spartan proof
//!   cargo run --release --example rs_shuffle_constraints -- spartan-zk # ZK Spartan proof

use ark_bn254::Fr as BaseField;
use ark_ec::{CurveConfig, PrimeGroup};
use ark_ff::UniformRand;
use ark_grumpkin::{GrumpkinConfig, Projective as GrumpkinProjective};
use ark_r1cs_std::alloc::AllocVar;
use ark_r1cs_std::fields::fp::FpVar;
use ark_r1cs_std::groups::curves::short_weierstrass::ProjectiveVar;
use ark_r1cs_std::prelude::AllocationMode;
use ark_relations::r1cs::ConstraintSystem;
use clap::{Parser, Subcommand};
use halo2curves::bn256::Fr as Bn256Fr;

use spartan2::rs_shuffle::bit_generation::derive_split_bits;
use spartan2::rs_shuffle::data_structures::PermutationWitnessTraceVar;
use spartan2::rs_shuffle::data_structures::{ElGamalCiphertext, ElGamalCiphertextVar};
use spartan2::rs_shuffle::encryption::ElGamalEncryption;
use spartan2::rs_shuffle::gadget::{rs_shuffle, rs_shuffle_with_reencryption};
use spartan2::rs_shuffle::native::run_rs_shuffle_permutation;

type GrumpkinVar = ProjectiveVar<GrumpkinConfig, FpVar<BaseField>>;

/// Standard deck size
const N: usize = 52;
/// Number of shuffle levels (log2(52) rounded up)
const LEVELS: usize = 6;

#[derive(Parser)]
#[command(name = "rs_shuffle_constraints")]
#[command(about = "RS Shuffle constraint counting and Spartan proof generation")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Just count constraints (no proof generation)
    Count,
    /// Generate non-ZK Spartan proof
    Spartan,
    /// Generate ZK Spartan proof
    SpartanZk,
}

fn main() {
    // Initialize tracing for timing breakdown
    use tracing_subscriber::EnvFilter;
    let _ = tracing_subscriber::fmt()
        .with_target(false)
        .with_env_filter(EnvFilter::from_default_env())
        .try_init();

    let cli = Cli::parse();

    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║         RS Shuffle Circuit Constraint Counter                ║");
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  N = {} cards, LEVELS = {}                                   ║",
        N, LEVELS
    );
    println!("╚══════════════════════════════════════════════════════════════╝\n");

    let mut rng = ark_std::test_rng();

    // Generate keys
    let sk = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
    let pk = GrumpkinProjective::generator() * sk;

    // Create initial ciphertexts (encrypted cards)
    println!("Creating {} encrypted cards...", N);
    let ct_init: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let message = <GrumpkinConfig as CurveConfig>::ScalarField::from(i as u64);
        let randomness = <GrumpkinConfig as CurveConfig>::ScalarField::rand(&mut rng);
        ElGamalCiphertext::encrypt_scalar(message, randomness, pk)
    });

    // Run native shuffle to generate witness
    println!("Running native RS shuffle...");
    let seed = BaseField::from(42u64);
    let rs_trace = run_rs_shuffle_permutation::<BaseField, _, N, LEVELS>(seed, &ct_init);

    // =========================================================================
    // Measure constraints for shuffle-only (without re-encryption)
    // =========================================================================
    println!("\n--- Shuffle Only (no re-encryption) ---");

    let cs_shuffle = ConstraintSystem::<BaseField>::new_ref();

    // Allocate circuit variables
    let ct_init_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_shuffle.clone(),
                || Ok(&ct_init[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate initial ciphertext")
        });

    let ct_shuffled_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_shuffle.clone(),
                || Ok(&rs_trace.permuted_output[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate shuffled ciphertext")
        });

    let witness_var = PermutationWitnessTraceVar::new_variable(
        cs_shuffle.clone(),
        || Ok(&rs_trace.witness_trace),
        AllocationMode::Witness,
    )
    .expect("Failed to allocate witness");

    let alpha = FpVar::new_input(cs_shuffle.clone(), || Ok(BaseField::from(17u64)))
        .expect("Failed to allocate alpha");
    let beta = FpVar::new_input(cs_shuffle.clone(), || Ok(BaseField::from(23u64)))
        .expect("Failed to allocate beta");

    let constraints_before = cs_shuffle.num_constraints();

    // Run the shuffle verification
    rs_shuffle::<GrumpkinProjective, GrumpkinVar, N, LEVELS>(
        cs_shuffle.clone(),
        &ct_init_vars,
        &ct_shuffled_vars,
        &witness_var,
        &alpha,
        &beta,
    )
    .expect("rs_shuffle failed");

    let constraints_after = cs_shuffle.num_constraints();
    let shuffle_constraints = constraints_after - constraints_before;

    println!("  Constraints before shuffle: {}", constraints_before);
    println!("  Constraints after shuffle:  {}", constraints_after);
    println!("  Shuffle-only constraints:   {}", shuffle_constraints);
    println!(
        "  Constraint system satisfied: {}",
        cs_shuffle.is_satisfied().unwrap()
    );

    // =========================================================================
    // Measure constraints for full circuit (with re-encryption)
    // =========================================================================
    println!("\n--- Full Circuit (with re-encryption) ---");

    let cs_full = ConstraintSystem::<BaseField>::new_ref();

    // Allocate seed
    let seed_var =
        FpVar::new_input(cs_full.clone(), || Ok(seed)).expect("Failed to allocate seed");

    // Allocate input ciphertexts
    let ct_input_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&ct_init[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate input ciphertext")
        });

    // Allocate shuffled ciphertexts (intermediate)
    let ct_shuffled_full: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&rs_trace.permuted_output[i]),
                AllocationMode::Witness,
            )
            .expect("Failed to allocate shuffled ciphertext")
        });

    // Generate re-encryption randomizations
    use ark_ff::{BigInteger, PrimeField};
    let rerandomizations: [BaseField; N] = std::array::from_fn(|_| BaseField::rand(&mut rng));

    // Compute re-encrypted output natively
    let ct_output: [ElGamalCiphertext<GrumpkinProjective>; N] = std::array::from_fn(|i| {
        let r_scalar = <GrumpkinConfig as CurveConfig>::ScalarField::from_le_bytes_mod_order(
            &rerandomizations[i].into_bigint().to_bytes_le(),
        );
        rs_trace.permuted_output[i].add_encryption_layer(r_scalar, &pk)
    });

    // Allocate output ciphertexts
    let ct_output_vars: [ElGamalCiphertextVar<GrumpkinProjective, GrumpkinVar>; N] =
        std::array::from_fn(|i| {
            ElGamalCiphertextVar::new_variable(
                cs_full.clone(),
                || Ok(&ct_output[i]),
                AllocationMode::Input,
            )
            .expect("Failed to allocate output ciphertext")
        });

    // Allocate public key
    let pk_var = GrumpkinVar::new_variable(cs_full.clone(), || Ok(pk), AllocationMode::Input)
        .expect("Failed to allocate public key");

    // Allocate challenges
    let alpha_full = FpVar::new_input(cs_full.clone(), || Ok(BaseField::from(17u64)))
        .expect("Failed to allocate alpha");
    let beta_full = FpVar::new_input(cs_full.clone(), || Ok(BaseField::from(23u64)))
        .expect("Failed to allocate beta");

    // Allocate witness
    let witness_full = PermutationWitnessTraceVar::new_variable(
        cs_full.clone(),
        || Ok(&rs_trace.witness_trace),
        AllocationMode::Witness,
    )
    .expect("Failed to allocate witness");

    // Allocate rerandomizations
    let rerand_vars: [FpVar<BaseField>; N] = std::array::from_fn(|i| {
        FpVar::new_witness(cs_full.clone(), || Ok(rerandomizations[i]))
            .expect("Failed to allocate rerandomization")
    });

    // Precompute generator powers
    let generator_powers = ElGamalEncryption::<GrumpkinProjective>::precompute_generator_powers();

    // Get number of Poseidon samples needed
    let (_, num_samples) = derive_split_bits::<BaseField, N, LEVELS>(seed);

    let constraints_before_full = cs_full.num_constraints();

    // Run the full verification
    rs_shuffle_with_reencryption::<GrumpkinProjective, GrumpkinVar, N, LEVELS>(
        cs_full.clone(),
        &seed_var,
        &ct_input_vars,
        &ct_shuffled_full,
        &ct_output_vars,
        &pk_var,
        &alpha_full,
        &beta_full,
        &witness_full,
        &rerand_vars,
        num_samples,
        &generator_powers,
    )
    .expect("rs_shuffle_with_reencryption failed");

    let constraints_after_full = cs_full.num_constraints();
    let full_constraints = constraints_after_full - constraints_before_full;

    println!("  Constraints before circuit: {}", constraints_before_full);
    println!("  Constraints after circuit:  {}", constraints_after_full);
    println!("  Full circuit constraints:   {}", full_constraints);
    println!(
        "  Constraint system satisfied: {}",
        cs_full.is_satisfied().unwrap()
    );

    // =========================================================================
    // Summary
    // =========================================================================
    println!("\n╔══════════════════════════════════════════════════════════════╗");
    println!("║                        SUMMARY                               ║");
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  Shuffle-only constraints:     {:>10}                   ║",
        shuffle_constraints
    );
    println!(
        "║  Full circuit constraints:     {:>10}                   ║",
        full_constraints
    );
    println!(
        "║  Re-encryption overhead:       {:>10}                   ║",
        full_constraints.saturating_sub(shuffle_constraints)
    );
    println!(
        "║  Constraints per card:         {:>10.1}                   ║",
        full_constraints as f64 / N as f64
    );
    println!("╚══════════════════════════════════════════════════════════════╝");

    // =========================================================================
    // Spartan Proof Generation (if requested)
    // =========================================================================
    match cli.command {
        Commands::Count => {
            println!("\n(Skipping proof generation - use 'spartan' or 'spartan-zk' subcommand)");
        }
        Commands::Spartan => {
            run_spartan_proof(&cs_full, constraints_after_full);
        }
        Commands::SpartanZk => {
            run_spartan_zk_proof(&cs_full, constraints_after_full);
        }
    }
}

fn run_spartan_proof(
    cs_full: &ark_relations::r1cs::ConstraintSystemRef<BaseField>,
    total_constraints: usize,
) {
    use spartan2::arkworks::{
        convert_constraint_matrices, extract_assignments, ArkworksCircuitAdapter,
    };
    use spartan2::provider::Bn254Engine;
    use spartan2::spartan::SpartanSNARK;
    use spartan2::traits::snark::R1CSSNARKTrait;
    use std::time::Instant;

    println!("\n--- Spartan (non-ZK) Proof ---");

    // Finalize the constraint system
    cs_full.finalize();

    // Extract matrices and assignments
    println!("  Extracting matrices and assignments...");
    let matrices = cs_full.to_matrices().expect("Failed to get matrices");
    let (a, b, c) = convert_constraint_matrices::<BaseField, Bn256Fr>(&matrices);
    let (w, x) = extract_assignments::<BaseField, Bn256Fr>(cs_full);

    println!(
        "  Matrices: {} constraints, {} witness vars, {} public inputs",
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1
    );

    // Create adapter
    let adapter = ArkworksCircuitAdapter::new(
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1,
        a,
        b,
        c,
        w,
        x,
    );

    // Setup
    println!("  Running Spartan setup...");
    let setup_start = Instant::now();
    let (pk, vk) = SpartanSNARK::<Bn254Engine>::setup(adapter.clone()).expect("Setup failed");
    let setup_time = setup_start.elapsed();
    println!("  Setup time: {:?}", setup_time);

    // Prep prove
    println!("  Running prep_prove...");
    let prep_start = Instant::now();
    let prep = SpartanSNARK::<Bn254Engine>::prep_prove(&pk, adapter.clone(), false)
        .expect("Prep prove failed");
    let prep_time = prep_start.elapsed();
    println!("  Prep time: {:?}", prep_time);

    // Prove
    println!("  Generating proof...");
    let prove_start = Instant::now();
    let snark = SpartanSNARK::<Bn254Engine>::prove(&pk, adapter, &prep, false)
        .expect("Proof generation failed");
    let prove_time = prove_start.elapsed();
    println!("  Prove time: {:?}", prove_time);

    // Verify
    println!("  Verifying proof...");
    let verify_start = Instant::now();
    let result = snark.verify(&vk);
    let verify_time = verify_start.elapsed();

    match result {
        Ok(public_outputs) => {
            println!("  ✓ Proof verified successfully!");
            println!("  Verify time: {:?}", verify_time);
            println!("  Public outputs: {} values", public_outputs.len());
        }
        Err(e) => {
            println!("  ✗ Verification failed: {:?}", e);
        }
    }

    print_spartan_summary(
        "SPARTAN (non-ZK)",
        setup_time,
        prep_time + prove_time,
        verify_time,
        total_constraints,
    );
}

fn run_spartan_zk_proof(
    cs_full: &ark_relations::r1cs::ConstraintSystemRef<BaseField>,
    total_constraints: usize,
) {
    use spartan2::arkworks::{
        convert_constraint_matrices, extract_assignments, ArkworksCircuitAdapter,
    };
    use spartan2::provider::Bn254Engine;
    use spartan2::spartan_zk::SpartanZkSNARK;
    use spartan2::traits::snark::R1CSSNARKTrait;
    use std::time::Instant;

    println!("\n--- Spartan zkSNARK Proof ---");

    // Finalize the constraint system
    cs_full.finalize();

    // Extract matrices and assignments
    println!("  Extracting matrices and assignments...");
    let matrices = cs_full.to_matrices().expect("Failed to get matrices");
    let (a, b, c) = convert_constraint_matrices::<BaseField, Bn256Fr>(&matrices);
    let (w, x) = extract_assignments::<BaseField, Bn256Fr>(cs_full);

    println!(
        "  Matrices: {} constraints, {} witness vars, {} public inputs",
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1
    );

    // Create adapter
    let adapter = ArkworksCircuitAdapter::new(
        matrices.num_constraints,
        matrices.num_witness_variables,
        matrices.num_instance_variables - 1,
        a,
        b,
        c,
        w,
        x,
    );

    // Setup
    println!("  Running Spartan setup...");
    let setup_start = Instant::now();
    let (pk, vk) = SpartanZkSNARK::<Bn254Engine>::setup(adapter.clone()).expect("Setup failed");
    let setup_time = setup_start.elapsed();
    println!("  Setup time: {:?}", setup_time);

    // Prep prove
    println!("  Running prep_prove...");
    let prep_start = Instant::now();
    let prep = SpartanZkSNARK::<Bn254Engine>::prep_prove(&pk, adapter.clone(), false)
        .expect("Prep prove failed");
    let prep_time = prep_start.elapsed();
    println!("  Prep time: {:?}", prep_time);

    // Prove
    println!("  Generating proof...");
    let prove_start = Instant::now();
    let snark = SpartanZkSNARK::<Bn254Engine>::prove(&pk, adapter, &prep, false)
        .expect("Proof generation failed");
    let prove_time = prove_start.elapsed();
    println!("  Prove time: {:?}", prove_time);

    // Verify
    println!("  Verifying proof...");
    let verify_start = Instant::now();
    let result = snark.verify(&vk);
    let verify_time = verify_start.elapsed();

    match result {
        Ok(public_outputs) => {
            println!("  ✓ Proof verified successfully!");
            println!("  Verify time: {:?}", verify_time);
            println!("  Public outputs: {} values", public_outputs.len());
        }
        Err(e) => {
            println!("  ✗ Verification failed: {:?}", e);
        }
    }

    print_spartan_summary(
        "SPARTAN zkSNARK",
        setup_time,
        prep_time + prove_time,
        verify_time,
        total_constraints,
    );
}

fn print_spartan_summary(
    name: &str,
    setup_time: std::time::Duration,
    prove_time: std::time::Duration,
    verify_time: std::time::Duration,
    total_constraints: usize,
) {
    println!("\n╔══════════════════════════════════════════════════════════════╗");
    println!(
        "║              {} PROOF SUMMARY                 ║",
        name
    );
    println!("╠══════════════════════════════════════════════════════════════╣");
    println!(
        "║  Setup time:                   {:>10.2?}                 ║",
        setup_time
    );
    println!(
        "║  Prove time:                   {:>10.2?}                 ║",
        prove_time
    );
    println!(
        "║  Verify time:                  {:>10.2?}                 ║",
        verify_time
    );
    println!(
        "║  Total constraints:            {:>10}                   ║",
        total_constraints
    );
    println!("╚══════════════════════════════════════════════════════════════╝");
}
