// THIS FILE IS AUTOGENERATED — Pallas curve constants
// Base field: p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
// Curve: y² = x³ + 5 (a=0, b=5)
#pragma once
#define NUM_LIMBS 16
#define NUM_LIMBS_WIDE 17
#define NUM_LIMBS_EXTRA_WIDE 32
#define LOG_LIMB_SIZE 16
#define TWO_POW_WORD_SIZE 65536
#define MASK 65535
#define N0 65535
#define NSAFE 1
#define SLACK 1
constant uint32_t BARRETT_MU[NUM_LIMBS] = {
    65532,
    65535,
    15435,
    39755,
    7057,
    56012,
    39951,
    30437,
    65535,
    65535,
    65535,
    65535,
    65535,
    65535,
    65535,
    65535
};
constant uint32_t CURVE_BASEFIELD_MODULUS[NUM_LIMBS] = {
    1,
    0,
    12525,
    39213,
    63771,
    2380,
    39164,
    8774,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    16384
};
constant uint32_t MONT_RADIX[NUM_LIMBS_WIDE] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1
};
constant uint32_t CURVE_ZERO_X[NUM_LIMBS] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ZERO_Y[NUM_LIMBS] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ZERO_Z[NUM_LIMBS] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ONE_X[NUM_LIMBS] = {
    0, 0, 12525, 39213, 63771, 2380, 39164, 8774, 0, 0, 0, 0, 0, 0, 0, 16384
};
constant uint32_t CURVE_ONE_Y[NUM_LIMBS] = {
    2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ONE_Z[NUM_LIMBS] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ZERO_XR[NUM_LIMBS] = {
    65533, 65535, 27960, 13432, 5293, 58393, 13579, 39212, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 16383
};
constant uint32_t CURVE_ZERO_YR[NUM_LIMBS] = {
    65533, 65535, 27960, 13432, 5293, 58393, 13579, 39212, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 16383
};
constant uint32_t CURVE_ZERO_ZR[NUM_LIMBS] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ONE_XR[NUM_LIMBS] = {
    4, 0, 50100, 25780, 58478, 9523, 25584, 35098, 0, 0, 0, 0, 0, 0, 0, 0
};
constant uint32_t CURVE_ONE_YR[NUM_LIMBS] = {
    65529, 65535, 43396, 53187, 12350, 48869, 53531, 4113, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 16383
};
constant uint32_t CURVE_ONE_ZR[NUM_LIMBS] = {
    65533, 65535, 27960, 13432, 5293, 58393, 13579, 39212, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 16383
};
