// Copyright (c) Microsoft Corporation.
// SPDX-License-Identifier: MIT
// This file is part of the Spartan2 project.
// See the LICENSE file in the project root for full license information.
// Source repository: https://github.com/Microsoft/Spartan2

//! This module implements the sum-check protocol used in Spartan.
//!
//! The sum-check protocol allows a prover to convince a verifier that a claimed sum
//! over a multivariate polynomial equals a specific value, without the verifier
//! needing to compute the sum directly.

use crate::{
  CommitmentKey,
  bellpepper::{
    r1cs::{MultiRoundSpartanWitness, MultiRoundState},
    solver::SatisfyingAssignment,
  },
  small_field::DelayedReduction,
  errors::SpartanError,
  polys::{
    multilinear::MultilinearPolynomial,
    univariate::{CompressedUniPoly, UniPoly},
  },
  r1cs::SplitMultiRoundR1CSShape,
  start_span,
  traits::{Engine, transcript::TranscriptEngineTrait},
  zk::{NeutronNovaVerifierCircuit, SpartanVerifierCircuit},
};
use ff::Field;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use tracing::info;

/// 4 k elements is a good cut-off on a 16-core machine.
pub(crate) const PAR_THRESHOLD: usize = 4 << 10; // 4096

/// Bind three polynomials to the same challenge in one pass.
/// More efficient than three separate bind calls - reduces Rayon dispatches
/// and uses serial fallback for small polynomials.
pub(crate) fn bind_three_polys_top<F: ff::PrimeField>(
  poly_a: &mut MultilinearPolynomial<F>,
  poly_b: &mut MultilinearPolynomial<F>,
  poly_c: &mut MultilinearPolynomial<F>,
  r: &F,
) {
  let n = poly_a.Z.len() / 2;
  debug_assert_eq!(poly_b.Z.len() / 2, n);
  debug_assert_eq!(poly_c.Z.len() / 2, n);

  let (a_lo, a_hi) = poly_a.Z.split_at_mut(n);
  let (b_lo, b_hi) = poly_b.Z.split_at_mut(n);
  let (c_lo, c_hi) = poly_c.Z.split_at_mut(n);

  if n >= PAR_THRESHOLD {
    // Parallel path - one Rayon dispatch for all three
    a_lo
      .par_iter_mut()
      .zip(a_hi.par_iter())
      .zip(b_lo.par_iter_mut())
      .zip(b_hi.par_iter())
      .zip(c_lo.par_iter_mut())
      .zip(c_hi.par_iter())
      .for_each(|(((((a_l, a_h), b_l), b_h), c_l), c_h)| {
        *a_l += *r * (*a_h - *a_l);
        *b_l += *r * (*b_h - *b_l);
        *c_l += *r * (*c_h - *c_l);
      });
  } else {
    // Serial path - no Rayon overhead
    for i in 0..n {
      a_lo[i] += *r * (a_hi[i] - a_lo[i]);
      b_lo[i] += *r * (b_hi[i] - b_lo[i]);
      c_lo[i] += *r * (c_hi[i] - c_lo[i]);
    }
  }

  poly_a.Z.truncate(n);
  poly_b.Z.truncate(n);
  poly_c.Z.truncate(n);
}

/// A proof generated by the sum-check protocol.
///
/// This struct contains the compressed univariate polynomials that constitute
/// the prover's messages in each round of the sum-check protocol.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(bound = "")]
pub struct SumcheckProof<E: Engine> {
  compressed_polys: Vec<CompressedUniPoly<E::Scalar>>,
}

impl<E: Engine> SumcheckProof<E> {
  /// Create a new sumcheck proof from compressed polynomials.
  pub(crate) fn new(compressed_polys: Vec<CompressedUniPoly<E::Scalar>>) -> Self {
    Self { compressed_polys }
  }

  /// Verifies a sum-check proof.
  ///
  /// # Arguments
  /// * `claim` - The claimed sum that the prover asserts
  /// * `num_rounds` - The number of rounds in the sum-check protocol
  /// * `degree_bound` - The maximum degree of univariate polynomials in each round
  /// * `transcript` - The transcript for the interactive proof
  ///
  /// # Returns
  /// A tuple containing the final evaluation point and the sequence of verifier challenges,
  /// or an error if verification fails.
  pub fn verify(
    &self,
    claim: E::Scalar,
    num_rounds: usize,
    degree_bound: usize,
    transcript: &mut E::TE,
  ) -> Result<(E::Scalar, Vec<E::Scalar>), SpartanError> {
    let (_verify_span, verify_t) = start_span!("sumcheck_verify");
    let mut e = claim;
    let mut r: Vec<E::Scalar> = Vec::new();

    // verify that there is a univariate polynomial for each round
    if self.compressed_polys.len() != num_rounds {
      return Err(SpartanError::InvalidSumcheckProof);
    }

    for i in 0..self.compressed_polys.len() {
      let (_round_span, round_t) = start_span!("sumcheck_verify_round", round = i);
      let poly = self.compressed_polys[i].decompress(&e);

      // verify degree bound
      if poly.degree() != degree_bound {
        return Err(SpartanError::InvalidSumcheckProof);
      }

      // we do not need to check if poly(0) + poly(1) = e, as
      // decompress() call above already ensures that holds
      debug_assert_eq!(poly.eval_at_zero() + poly.eval_at_one(), e);

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;

      r.push(r_i);

      // evaluate the claimed degree-ell polynomial at r_i
      e = poly.evaluate(&r_i);

      if round_t.elapsed().as_millis() > 0 {
        info!(elapsed_ms = %round_t.elapsed().as_millis(), "sumcheck_verify_round");
      }
    }

    info!(elapsed_ms = %verify_t.elapsed().as_millis(), "sumcheck_verify");
    Ok((e, r))
  }

  /// Computes BDDT evaluation points for a quadratic polynomial: (p(0), leading_coeff).
  ///
  /// Uses delayed modular reduction. The leading coefficient of p(X) = A(X)·B(X)
  /// is Σ (a_high - a_low)(b_high - b_low), saving 2 doubles + 2 adds per element
  /// vs computing eval_at_2.
  ///
  /// # Returns
  /// A tuple `(p0, leading)` — use `UniPoly::from_evals_deg2(p0, leading, claim)`.
  #[inline]
  pub(crate) fn compute_eval_points_quad(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar)
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    type Acc<S> = <S as DelayedReduction<S>>::Accumulator;

    let len = poly_A.Z.len() / 2;

    let (acc_0, acc_leading) = (0..len)
      .into_par_iter()
      .fold(
        || (Acc::<E::Scalar>::default(), Acc::<E::Scalar>::default()),
        |mut acc, i| {
          let a_low = &poly_A[i];
          let a_high = &poly_A[len + i];
          let b_low = &poly_B[i];
          let b_high = &poly_B[len + i];

          // p(0): a_low × b_low
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut acc.0, a_low, b_low,
          );

          // leading coeff: (a_high - a_low) × (b_high - b_low)
          let da = *a_high - *a_low;
          let db = *b_high - *b_low;
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut acc.1, &da, &db,
          );

          acc
        },
      )
      .reduce(
        || (Acc::<E::Scalar>::default(), Acc::<E::Scalar>::default()),
        |mut a, b| {
          a.0 += b.0;
          a.1 += b.1;
          a
        },
      );

    (
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_0),
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_leading),
    )
  }

  /// Generates a sum-check proof for a quadratic combination of two multilinear polynomials.
  ///
  /// Uses delayed modular reduction for improved performance.
  ///
  /// # Arguments
  /// * `claim` - The claimed sum over the hypercube
  /// * `num_rounds` - The number of variables/rounds in the sum-check
  /// * `poly_A` - First multilinear polynomial (mutable, will be bound during protocol)
  /// * `poly_B` - Second multilinear polynomial (mutable, will be bound during protocol)
  /// * `transcript` - The transcript for generating randomness
  ///
  /// # Returns
  /// A tuple containing the sum-check proof, the sequence of verifier challenges,
  /// and the final evaluations of the polynomials.
  pub fn prove_quad(
    claim: &E::Scalar,
    num_rounds: usize,
    poly_A: &mut MultilinearPolynomial<E::Scalar>,
    poly_B: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), SpartanError>
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;
    for round in 0..num_rounds {
      let (_round_span, round_t) = start_span!("sumcheck_quad_round", round = round);

      let poly = {
        let (_eval_span, eval_t) = start_span!("compute_eval_points_quad");
        let (p0, leading) = Self::compute_eval_points_quad(poly_A, poly_B);
        if eval_t.elapsed().as_millis() > 0 {
          info!(elapsed_ms = %eval_t.elapsed().as_millis(), "compute_eval_points_quad");
        }

        UniPoly::from_evals_deg2(p0, leading, claim_per_round)
      };

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round
      claim_per_round = poly.evaluate(&r_i);

      // bind all tables to the verifier's challenge
      let (_bind_span, bind_t) = start_span!("bind_poly_vars_quad");
      rayon::join(
        || poly_A.bind_poly_var_top(&r_i),
        || poly_B.bind_poly_var_top(&r_i),
      );
      info!(elapsed_ms = %bind_t.elapsed().as_millis(), "bind_poly_vars_quad");
      info!(elapsed_ms = %round_t.elapsed().as_millis(), round = round, "sumcheck_quad_round");
    }

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      vec![poly_A[0], poly_B[0]],
    ))
  }

  /// Computes BDDT evaluation points for cubic polynomial: a * (b * c - d).
  ///
  /// Returns (p(0), leading_coeff, p(-1)) instead of (eval_0, eval_2, eval_3).
  /// Leading coeff of degree-3 term = da·(db·dc) where dx = x_high - x_low.
  /// Saves 4 doubles + 4 adds per element vs evaluating at points 2 and 3.
  ///
  /// # Returns
  /// A tuple `(p0, leading, p_neg1)` — use `UniPoly::from_evals_deg3`.
  #[inline]
  fn compute_eval_points_cubic_with_additive_term(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
    poly_C: &MultilinearPolynomial<E::Scalar>,
    poly_D: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar, E::Scalar)
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    type Acc<S> = <S as DelayedReduction<S>>::Accumulator;

    let len = poly_B.Z.len() / 2;

    let (acc_0, acc_leading, acc_neg1) = (0..len)
      .into_par_iter()
      .fold(
        || {
          (
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
          )
        },
        |mut acc, i| {
          let a_low = &poly_A[i];
          let a_high = &poly_A[i + len];
          let b_low = &poly_B[i];
          let b_high = &poly_B[i + len];
          let c_low = &poly_C[i];
          let c_high = &poly_C[i + len];
          let d_low = &poly_D[i];
          let d_high = &poly_D[i + len];

          // p(0): a_low * (b_low * c_low - d_low)
          let inner_0 = *b_low * *c_low - *d_low;
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut acc.0, a_low, &inner_0,
          );

          // Differences for leading coeff and p(-1)
          let da = *a_high - *a_low;
          let db = *b_high - *b_low;
          let dc = *c_high - *c_low;
          let dd = *d_high - *d_low;

          // Leading coeff (degree 3): da * (db * dc)
          // No dd term — A*D is only degree 2
          let inner_leading = db * dc;
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut acc.1, &da, &inner_leading,
          );

          // p(-1): a_neg * (b_neg * c_neg - d_neg)
          let a_neg = *a_low - da;
          let b_neg = *b_low - db;
          let c_neg = *c_low - dc;
          let d_neg = *d_low - dd;
          let inner_neg = b_neg * c_neg - d_neg;
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut acc.2, &a_neg, &inner_neg,
          );

          acc
        },
      )
      .reduce(
        || {
          (
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
          )
        },
        |mut a, b| {
          a.0 += b.0;
          a.1 += b.1;
          a.2 += b.2;
          a
        },
      );

    (
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_0),
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_leading),
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_neg1),
    )
  }

  #[inline]
  /// Computes BDDT evaluation points for cubic with additive term and outer pow_tau.
  ///
  /// Returns (p(0), leading_coeff, p(-1)) using two-level delayed reduction.
  /// Falls back to `compute_eval_points_cubic_with_additive_term` when len < left.
  fn compute_eval_points_cubic_with_additive_term_with_outer_pow(
    pow_tau_left: &MultilinearPolynomial<E::Scalar>,
    pow_tau_right: &MultilinearPolynomial<E::Scalar>,
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
    poly_C: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar, E::Scalar)
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    type Acc<S> = <S as DelayedReduction<S>>::Accumulator;

    let len = poly_A.Z.len() / 2;
    let left = pow_tau_left.Z.len();

    if len < left {
      return Self::compute_eval_points_cubic_with_additive_term(
        pow_tau_left,
        poly_A,
        poly_B,
        poly_C,
      );
    }

    let right = len / left;

    let (acc_0, acc_leading, acc_neg1) = (0..left)
      .into_par_iter()
      .fold(
        || {
          (
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
          )
        },
        |mut outer_acc, i| {
          let pow_left = &pow_tau_left[i];

          // Inner loop: accumulate in wide limbs
          let mut inner_0 = Acc::<E::Scalar>::default();
          let mut inner_leading = Acc::<E::Scalar>::default();
          let mut inner_neg1 = Acc::<E::Scalar>::default();

          for j in 0..right {
            let low = i + j * left;
            let high = low + len;

            let tau_low = &pow_tau_right[j];
            let tau_high = &pow_tau_right[j + right];
            let a_low = &poly_A[low];
            let a_high = &poly_A[high];
            let b_low = &poly_B[low];
            let b_high = &poly_B[high];
            let c_low = &poly_C[low];
            let c_high = &poly_C[high];

            // p(0): tau_low * (a_low * b_low - c_low)
            let prod_0 = *a_low * *b_low - *c_low;
            <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
              &mut inner_0,
              tau_low,
              &prod_0,
            );

            // Differences
            let d_tau = *tau_high - *tau_low;
            let da = *a_high - *a_low;
            let db = *b_high - *b_low;
            let dc = *c_high - *c_low;

            // Leading coeff (degree 3): d_tau * da * (db * dc)
            // Wait — this is tau * a * (b*c - d) with d=poly_C.
            // The full polynomial is tau(X) * a(X) * b(X) - tau(X) * a(X) * c(X)
            // which is degree 4 in X... but we're computing a degree 3 polynomial
            // because tau(X)*a(X)*(b(X)*c(X) - d(X)).
            // Hmm, actually this function computes tau * (a * b - c), degree 3.
            // Leading of tau*a*b = d_tau * da * db (degree 3)
            // Leading of tau*c = d_tau * dc (degree 2, not 3)
            // So degree-3 leading = d_tau * da * db
            let prod_leading = da * db;
            <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
              &mut inner_leading,
              &d_tau,
              &prod_leading,
            );

            // p(-1): tau_neg * (a_neg * b_neg - c_neg)
            let tau_neg = *tau_low - d_tau;
            let a_neg = *a_low - da;
            let b_neg = *b_low - db;
            let c_neg = *c_low - dc;
            let prod_neg = a_neg * b_neg - c_neg;
            <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
              &mut inner_neg1,
              &tau_neg,
              &prod_neg,
            );
          }

          // Reduce inner sums, accumulate into outer accumulators
          let inner_0_red = <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_0);
          let inner_leading_red =
            <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_leading);
          let inner_neg1_red = <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_neg1);

          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut outer_acc.0,
            pow_left,
            &inner_0_red,
          );
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut outer_acc.1,
            pow_left,
            &inner_leading_red,
          );
          <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
            &mut outer_acc.2,
            pow_left,
            &inner_neg1_red,
          );

          outer_acc
        },
      )
      .reduce(
        || {
          (
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
            Acc::<E::Scalar>::default(),
          )
        },
        |mut a, b| {
          a.0 += b.0;
          a.1 += b.1;
          a.2 += b.2;
          a
        },
      );

    (
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_0),
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_leading),
      <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_neg1),
    )
  }

  /// Prove poly_A * poly_B - poly_C using optimized equality polynomial handling
  pub fn prove_cubic_with_three_inputs(
    claim: &E::Scalar,
    taus: Vec<E::Scalar>,
    poly_A: &mut MultilinearPolynomial<E::Scalar>,
    poly_B: &mut MultilinearPolynomial<E::Scalar>,
    poly_C: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), SpartanError> {
    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;

    let num_rounds = taus.len();

    let mut eq_instance = eq_sumcheck::EqSumCheckInstance::<E>::new(taus);

    for round in 0..num_rounds {
      let (_round_span, round_t) = start_span!("sumcheck_round", round = round);

      let poly = {
        // Make an iterator returning the contributions to the evaluations
        let (_eval_span, eval_t) = start_span!("compute_eval_points");
        let (p0, leading, p_neg1) =
          eq_instance.evaluation_points_cubic_with_three_inputs(round, poly_A, poly_B, poly_C);
        if eval_t.elapsed().as_millis() > 0 {
          info!(elapsed_ms = %eval_t.elapsed().as_millis(), "compute_eval_points");
        }

        UniPoly::from_evals_deg3(p0, leading, p_neg1, claim_per_round)
      };

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round
      claim_per_round = poly.evaluate(&r_i);

      // bound all tables to the verifier's challenge
      let (_bind_span, bind_t) = start_span!("bind_poly_vars");
      rayon::join(
        || poly_A.bind_poly_var_top(&r_i),
        || poly_B.bind_poly_var_top(&r_i),
      );
      rayon::join(
        || poly_C.bind_poly_var_top(&r_i),
        || eq_instance.bound(&r_i),
      );
      info!(elapsed_ms = %bind_t.elapsed().as_millis(), "bind_poly_vars");
      info!(elapsed_ms = %round_t.elapsed().as_millis(), round = round, "sumcheck_round");
    }

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      vec![poly_A[0], poly_B[0], poly_C[0]],
    ))
  }

  /// Prove poly_A * poly_B - poly_C using split-eq with delayed modular reduction.
  ///
  /// Same as `prove_cubic_with_three_inputs` but uses delayed modular reduction
  /// in the eq polynomial evaluation to reduce Montgomery reductions from O(2^k)
  /// to O(2^{k/2}) per round. This isolates the delayed reduction optimization
  /// without small-value accumulator precomputation.
  pub fn prove_cubic_with_three_inputs_split_eq_delayed(
    claim: &E::Scalar,
    taus: Vec<E::Scalar>,
    poly_A: &mut MultilinearPolynomial<E::Scalar>,
    poly_B: &mut MultilinearPolynomial<E::Scalar>,
    poly_C: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), SpartanError>
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;

    let num_rounds = taus.len();

    let mut eq_instance = eq_sumcheck::EqSumCheckInstance::<E>::new(taus);

    for round in 0..num_rounds {
      let (_round_span, round_t) = start_span!("sumcheck_round", round = round);

      let poly = {
        let (_eval_span, eval_t) = start_span!("compute_eval_points");
        // Use delayed modular reduction version
        let (p0, leading, p_neg1) = eq_instance
          .evaluation_points_cubic_with_three_inputs_delayed(round, poly_A, poly_B, poly_C);
        if eval_t.elapsed().as_millis() > 0 {
          info!(elapsed_ms = %eval_t.elapsed().as_millis(), "compute_eval_points");
        }

        UniPoly::from_evals_deg3(p0, leading, p_neg1, claim_per_round)
      };

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round
      claim_per_round = poly.evaluate(&r_i);

      // bound all tables to the verifier's challenge
      let (_bind_span, bind_t) = start_span!("bind_poly_vars");
      bind_three_polys_top(poly_A, poly_B, poly_C, &r_i);
      eq_instance.bound(&r_i);
      info!(elapsed_ms = %bind_t.elapsed().as_millis(), "bind_poly_vars");
      info!(elapsed_ms = %round_t.elapsed().as_millis(), round = round, "sumcheck_round");
    }

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      vec![poly_A[0], poly_B[0], poly_C[0]],
    ))
  }

  /// Executes the **outer** cubic-with-additive-term sum-check in
  /// Zero-knowledge outer sum-check for the cubic-with-additive-term case.
  pub fn prove_cubic_with_additive_term_zk(
    num_rounds: usize,
    taus: &[E::Scalar],
    poly_Az: &mut MultilinearPolynomial<E::Scalar>,
    poly_Bz: &mut MultilinearPolynomial<E::Scalar>,
    poly_Cz: &mut MultilinearPolynomial<E::Scalar>,
    verifier_circuit: &mut SpartanVerifierCircuit<E>,
    state: &mut MultiRoundState<E>,
    vc_shape: &SplitMultiRoundR1CSShape<E>,
    vc_ck: &CommitmentKey<E>,
    transcript: &mut E::TE,
  ) -> Result<Vec<E::Scalar>, SpartanError> {
    let mut r_x: Vec<E::Scalar> = Vec::with_capacity(num_rounds);
    let mut claim_outer_round = E::Scalar::ZERO;
    let mut eq_instance = eq_sumcheck::EqSumCheckInstance::<E>::new(taus.to_vec());

    for i in 0..num_rounds {
      // -------- interpolate coefficients --------

      let (p0, leading, p_neg1) =
        eq_instance.evaluation_points_cubic_with_three_inputs(i, poly_Az, poly_Bz, poly_Cz);
      let poly = UniPoly::from_evals_deg3(p0, leading, p_neg1, claim_outer_round);
      verifier_circuit.outer_polys[i] = [
        poly.coeffs[0],
        poly.coeffs[1],
        poly.coeffs[2],
        poly.coeffs[3],
      ];

      // -------- transcript / witness handling --------
      let chals = SatisfyingAssignment::<E>::process_round(
        state,
        vc_shape,
        vc_ck,
        verifier_circuit,
        i,
        transcript,
      )?;
      r_x.push(chals[0]);

      // -------- advance claim and bind polys --------
      claim_outer_round = poly.evaluate(&chals[0]);

      rayon::join(
        || poly_Az.bind_poly_var_top(&chals[0]),
        || {
          rayon::join(
            || poly_Bz.bind_poly_var_top(&chals[0]),
            || poly_Cz.bind_poly_var_top(&chals[0]),
          );
        },
      );
      eq_instance.bound(&chals[0]);
    }

    Ok(r_x)
  }

  /// Executes a **quadratic** sum-check in zero-knowledge mode and returns the
  /// Zero-knowledge quadratic sum-check used for the inner round.
  ///
  /// Uses delayed modular reduction for improved performance.
  pub fn prove_quad_zk(
    claim: &E::Scalar,
    num_rounds: usize,
    poly_ABC: &mut MultilinearPolynomial<E::Scalar>,
    poly_z: &mut MultilinearPolynomial<E::Scalar>,
    verifier_circuit: &mut SpartanVerifierCircuit<E>,
    state: &mut MultiRoundState<E>,
    vc_shape: &SplitMultiRoundR1CSShape<E>,
    vc_ck: &CommitmentKey<E>,
    transcript: &mut E::TE,
    start_round: usize,
  ) -> Result<(Vec<E::Scalar>, Vec<E::Scalar>), SpartanError>
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    let mut r_y: Vec<E::Scalar> = Vec::with_capacity(num_rounds);
    let mut claim_current_round = *claim;

    for j in 0..num_rounds {
      // -------- interpolate coeffs --------
      let (p0, leading) = Self::compute_eval_points_quad(poly_ABC, poly_z);
      let poly = UniPoly::from_evals_deg2(p0, leading, claim_current_round);

      verifier_circuit.inner_polys[j] = [poly.coeffs[0], poly.coeffs[1], poly.coeffs[2]];

      // -------- transcript / witness handling --------
      let chals = SatisfyingAssignment::<E>::process_round(
        state,
        vc_shape,
        vc_ck,
        verifier_circuit,
        start_round + j,
        transcript,
      )?;
      r_y.push(chals[0]);

      // -------- bind polys --------
      rayon::join(
        || poly_ABC.bind_poly_var_top(&chals[0]),
        || poly_z.bind_poly_var_top(&chals[0]),
      );

      // -------- advance claim for next round --------
      claim_current_round = poly.evaluate(&chals[0]);
    }

    Ok((r_y, vec![poly_ABC[0], poly_z[0]]))
  }

  /// Executes a **quadratic** batched sum-check in zero-knowledge mode and returns the
  /// sequence of verifier challenges used for the inner round.
  ///
  /// Uses delayed modular reduction for improved performance.
  pub fn prove_quad_batched_zk(
    claims: &[E::Scalar; 2],
    num_rounds: usize,
    poly_A_0: &mut MultilinearPolynomial<E::Scalar>,
    poly_A_1: &mut MultilinearPolynomial<E::Scalar>,
    poly_B_0: &mut MultilinearPolynomial<E::Scalar>,
    poly_B_1: &mut MultilinearPolynomial<E::Scalar>,
    verifier_circuit: &mut NeutronNovaVerifierCircuit<E>,
    state: &mut MultiRoundState<E>,
    vc_shape: &SplitMultiRoundR1CSShape<E>,
    vc_ck: &CommitmentKey<E>,
    transcript: &mut E::TE,
    start_round: usize,
  ) -> Result<(Vec<E::Scalar>, Vec<E::Scalar>), SpartanError>
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    let mut r_y: Vec<E::Scalar> = Vec::with_capacity(num_rounds);
    // Maintain separate claims for step and core branches
    let mut claim_step_round = claims[0];
    let mut claim_core_round = claims[1];

    for j in 0..num_rounds {
      // -------- interpolate coeffs --------
      let ((p0_s, leading_s), (p0_c, leading_c)) = rayon::join(
        || Self::compute_eval_points_quad(poly_A_0, poly_B_0),
        || Self::compute_eval_points_quad(poly_A_1, poly_B_1),
      );

      // step branch
      let poly_s = UniPoly::from_evals_deg2(p0_s, leading_s, claim_step_round);
      let coeffs_step = [poly_s.coeffs[0], poly_s.coeffs[1], poly_s.coeffs[2]];

      // core branch
      let poly_c = UniPoly::from_evals_deg2(p0_c, leading_c, claim_core_round);
      let coeffs_core = [poly_c.coeffs[0], poly_c.coeffs[1], poly_c.coeffs[2]];

      verifier_circuit.inner_polys_step[j] = coeffs_step;
      verifier_circuit.inner_polys_core[j] = coeffs_core;

      // -------- transcript / witness handling --------
      let chals = SatisfyingAssignment::<E>::process_round(
        state,
        vc_shape,
        vc_ck,
        verifier_circuit,
        start_round + j,
        transcript,
      )?;
      let r_j = chals[0];
      r_y.push(r_j);

      // -------- bind polys --------
      rayon::join(
        || {
          rayon::join(
            || poly_A_0.bind_poly_var_top(&r_j),
            || poly_B_0.bind_poly_var_top(&r_j),
          );
        },
        || {
          rayon::join(
            || poly_A_1.bind_poly_var_top(&r_j),
            || poly_B_1.bind_poly_var_top(&r_j),
          );
        },
      );

      // -------- advance claim for next round --------
      claim_step_round = poly_s.evaluate(&r_j);
      claim_core_round = poly_c.evaluate(&r_j);
    }

    Ok((
      r_y,
      vec![poly_A_0[0], poly_A_1[0], poly_B_0[0], poly_B_1[0]],
    ))
  }

  /// Executes a **cubic-with-additive-term** batched outer sum-check in zero-knowledge mode
  /// and returns the sequence of verifier challenges.
  pub fn prove_cubic_with_additive_term_batched_zk(
    num_rounds: usize,
    pow_tau_left: &mut MultilinearPolynomial<E::Scalar>,
    pow_tau_right: &MultilinearPolynomial<E::Scalar>,
    poly_A_step: &mut MultilinearPolynomial<E::Scalar>,
    poly_A_core: &mut MultilinearPolynomial<E::Scalar>,
    poly_B_step: &mut MultilinearPolynomial<E::Scalar>,
    poly_B_core: &mut MultilinearPolynomial<E::Scalar>,
    poly_C_step: &mut MultilinearPolynomial<E::Scalar>,
    poly_C_core: &mut MultilinearPolynomial<E::Scalar>,
    verifier_circuit: &mut NeutronNovaVerifierCircuit<E>,
    state: &mut MultiRoundState<E>,
    vc_shape: &SplitMultiRoundR1CSShape<E>,
    vc_ck: &CommitmentKey<E>,
    transcript: &mut E::TE,
    start_round: usize,
  ) -> Result<Vec<E::Scalar>, SpartanError>
  where
    E::Scalar: DelayedReduction<E::Scalar>,
  {
    let mut base_tau = E::Scalar::ONE;
    let mut len_pow_tau = pow_tau_left.Z.len() * pow_tau_right.Z.len();

    let mut r_x: Vec<E::Scalar> = Vec::with_capacity(num_rounds);

    let mut claim_step = verifier_circuit.t_out_step;
    let mut claim_core = E::Scalar::ZERO;

    for i in 0..num_rounds {
      // step branch
      let ((mut p0_s, mut leading_s, mut neg1_s), (mut p0_c, mut leading_c, mut neg1_c)) =
        rayon::join(
          || {
            Self::compute_eval_points_cubic_with_additive_term_with_outer_pow(
              pow_tau_left,
              pow_tau_right,
              poly_A_step,
              poly_B_step,
              poly_C_step,
            )
          },
          || {
            Self::compute_eval_points_cubic_with_additive_term_with_outer_pow(
              pow_tau_left,
              pow_tau_right,
              poly_A_core,
              poly_B_core,
              poly_C_core,
            )
          },
        );

      p0_s *= base_tau;
      leading_s *= base_tau;
      neg1_s *= base_tau;
      p0_c *= base_tau;
      leading_c *= base_tau;
      neg1_c *= base_tau;

      let poly_s = UniPoly::from_evals_deg3(p0_s, leading_s, neg1_s, claim_step);
      let coeffs_step = [
        poly_s.coeffs[0],
        poly_s.coeffs[1],
        poly_s.coeffs[2],
        poly_s.coeffs[3],
      ];

      let poly_c = UniPoly::from_evals_deg3(p0_c, leading_c, neg1_c, claim_core);
      let coeffs_core = [
        poly_c.coeffs[0],
        poly_c.coeffs[1],
        poly_c.coeffs[2],
        poly_c.coeffs[3],
      ];

      verifier_circuit.outer_polys_step[i] = coeffs_step;
      verifier_circuit.outer_polys_core[i] = coeffs_core;

      // -------- transcript / witness handling --------
      let chals = SatisfyingAssignment::<E>::process_round(
        state,
        vc_shape,
        vc_ck,
        verifier_circuit,
        start_round + i,
        transcript,
      )?;
      let r_i = chals[0];
      r_x.push(r_i);

      // -------- advance claim and bind polys --------
      claim_step = poly_s.evaluate(&r_i);
      claim_core = poly_c.evaluate(&r_i);

      // bind polynomials to the verifier's challenge
      rayon::join(
        || {
          rayon::join(
            || poly_A_step.bind_poly_var_top(&r_i),
            || poly_A_core.bind_poly_var_top(&r_i),
          );
        },
        || {
          rayon::join(
            || {
              rayon::join(
                || poly_B_step.bind_poly_var_top(&r_i),
                || poly_B_core.bind_poly_var_top(&r_i),
              );
            },
            || {
              rayon::join(
                || poly_C_step.bind_poly_var_top(&r_i),
                || poly_C_core.bind_poly_var_top(&r_i),
              );
            },
          );
        },
      );

      // bind polynomial power of tau
      // list power of tau (pow_tau) halves effectively
      len_pow_tau >>= 1;
      let one = E::Scalar::ONE;
      let left = pow_tau_left.Z.len();
      let pow = pow_tau_left.Z[len_pow_tau % left] * pow_tau_right.Z[len_pow_tau / left];
      base_tau *= (pow - one) * r_i + one;
    }

    pow_tau_left.Z[0] = base_tau;

    Ok(r_x)
  }
}

pub(crate) mod eq_sumcheck {
  //! This module implements the sumcheck optimization for equality polynomials.
  //! The optimization is described in Section 5 of <https://eprint.iacr.org/2025/1117> algorithm 5.
  use crate::{
    polys::multilinear::MultilinearPolynomial, small_field::DelayedReduction, traits::Engine,
  };
  use ff::{Field, PrimeField};
  use rayon::{iter::ZipEq, prelude::*, slice::Iter};

  pub struct EqSumCheckInstance<E: Engine> {
    // number of variables at first
    init_num_vars: usize,
    first_half: usize,
    second_half: usize,
    round: usize,
    taus: Vec<E::Scalar>,
    eval_eq_left: E::Scalar,
    poly_eq_left: Vec<Vec<E::Scalar>>,
    poly_eq_right: Vec<Vec<E::Scalar>>,
    eq_tau_0_leading_neg1: Vec<(E::Scalar, E::Scalar, E::Scalar)>,
  }

  impl<E: Engine> EqSumCheckInstance<E> {
    /// Creates a new EqSumCheckInstance for optimized sumcheck with equality polynomials.
    ///
    /// The algorithm splits the tau vector and precomputes equality polynomial evaluations
    /// for efficient lookup during the sumcheck rounds. The round counter starts at 1 (not 0)
    /// to simplify indexing into precomputed arrays, as the first evaluation happens before
    /// any binding operations occur.
    pub fn new(taus: Vec<E::Scalar>) -> Self {
      let l = taus.len();
      let first_half = l / 2;

      let compute_eq_polynomials = |taus: Vec<&E::Scalar>| -> Vec<Vec<E::Scalar>> {
        let len = taus.len();
        let mut result = Vec::with_capacity(len + 1);

        result.push(vec![E::Scalar::ONE]);

        for i in 0..len {
          let tau = taus[i];

          let prev = &result[i];
          let mut v_next = prev.to_vec();
          v_next.par_extend(prev.par_iter().map(|v| *v * tau));
          let (first, last) = v_next.split_at_mut(prev.len());
          first.par_iter_mut().zip(last).for_each(|(a, b)| *a -= *b);

          result.push(v_next);
        }

        result
      };

      let (left_taus, right_taus) = taus.split_at(first_half);
      // Skip the first element of left_taus because the equality polynomial evaluation
      // for the first variable is tracked separately in eval_eq_left (initialized to 1).
      // This matches the Nova optimization approach where the left part is processed
      // incrementally through the bound() method rather than via lookup tables.
      let left_taus = left_taus.iter().skip(1).rev().collect::<Vec<_>>();
      let right_taus = right_taus.iter().rev().collect::<Vec<_>>();

      let (poly_eq_left, poly_eq_right) = rayon::join(
        || compute_eq_polynomials(left_taus),
        || compute_eq_polynomials(right_taus),
      );

      let f1 = E::Scalar::ONE;
      let f2 = f1.double();
      let eq_tau_0_leading_neg1 = taus
        .par_iter()
        .map(|tau| {
          let tau2 = tau.double();
          let tau3 = tau2 + tau;
          // eq(τ,0) = 1-τ, eq_leading = 2τ-1, eq(τ,-1) = 2-3τ
          (f1 - tau, tau2 - f1, f2 - tau3)
        })
        .collect::<Vec<_>>();

      Self {
        init_num_vars: l,
        first_half,
        second_half: l - first_half,
        round: 1, // Start at 1 to simplify array indexing (round-1 gives 0-based index)
        taus,
        eval_eq_left: E::Scalar::ONE,
        poly_eq_left,
        poly_eq_right,
        eq_tau_0_leading_neg1,
      }
    }

    /// Evaluate poly_A * poly_B - poly_C
    #[inline]
    pub fn evaluation_points_cubic_with_three_inputs(
      &self,
      round_idx: usize,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
      poly_C: &MultilinearPolynomial<E::Scalar>,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      debug_assert_eq!(poly_A.Z.len() % 2, 0);

      let in_first_half = self.round < self.first_half;

      let half_p = poly_A.Z.len() / 2;

      let [zip_A, zip_B, zip_C] = split_and_zip([&poly_A.Z, &poly_B.Z, &poly_C.Z], half_p);

      let (mut q0, mut q_leading, mut q_neg1) = if in_first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();

        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .enumerate()
          .map(|(id, ((a, b), c))| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;
            let (zero_c, one_c) = c;

            let (q0, q_leading, q_neg1) = eval_one_case_cubic_three_inputs(
              round_idx, zero_a, one_a, zero_b, one_b, zero_c, one_c,
            );

            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            (q0 * factor, q_leading * factor, q_neg1 * factor)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
          )
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();

        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .zip_eq(poly_eq_right)
          .map(|(((a, b), c), poly_eq_right)| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;
            let (zero_c, one_c) = c;

            let (q0, q_leading, q_neg1) = eval_one_case_cubic_three_inputs(
              round_idx, zero_a, one_a, zero_b, one_b, zero_c, one_c,
            );

            let factor = poly_eq_right;

            (q0 * factor, q_leading * factor, q_neg1 * factor)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
          )
      };

      self.update_evals(&mut q0, &mut q_leading, &mut q_neg1);

      (q0, q_leading, q_neg1)
    }

    /// Evaluate poly_A * poly_B - poly_C using delayed reduction.
    ///
    /// Same as `evaluation_points_cubic_with_three_inputs` but uses delayed modular reduction
    /// to reduce Montgomery reductions from O(2^k) to O(2^{k/2}) per round.
    ///
    /// # Algorithm
    ///
    /// Uses two-phase accumulation with the split-eq factorization:
    /// - E[id] = E_out[x_out] * E_in[x_in] where id = (x_out, x_in)
    ///
    /// Phase 1 (inner): For each x_out, accumulate ∑_{x_in} E_in[x_in] ⊗ q_k(g) in wide limbs
    /// Phase 2 (outer): Reduce once, then accumulate E_out[x_out] ⊗ inner_reduced
    /// Final: Reduce once at the end
    #[inline]
    pub fn evaluation_points_cubic_with_three_inputs_delayed(
      &self,
      round_idx: usize,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
      poly_C: &MultilinearPolynomial<E::Scalar>,
    ) -> (E::Scalar, E::Scalar, E::Scalar)
    where
      E::Scalar: DelayedReduction<E::Scalar>,
    {
      debug_assert_eq!(poly_A.Z.len() % 2, 0);

      type Acc<S> = <S as DelayedReduction<S>>::Accumulator;

      let in_first_half = self.round < self.first_half;
      let half_p = poly_A.Z.len() / 2;

      let (mut q0, mut q_leading, mut q_neg1) = if in_first_half {
        // Two-phase accumulation: E[id] = E_out[x_out] * E_in[x_in]
        let (poly_eq_left, poly_eq_right, second_half, _low_mask) = self.poly_eqs_first_half();
        let eq_out_len = poly_eq_left.len();

        // Outer loop: iterate over E_out indices
        // Dynamic chunk size: enough chunks for work-stealing, but not too many to cause overhead
        let min_chunk = (eq_out_len / (rayon::current_num_threads() * 4)).max(1);
        let (acc_0, acc_leading, acc_neg1) = (0..eq_out_len)
          .into_par_iter()
          .with_min_len(min_chunk)
          .fold(
            || {
              (
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
              )
            },
            |mut outer_acc, x_out| {
              let e_out = &poly_eq_left[x_out];

              // Phase 1: Inner loop - accumulate E_in[x_in] ⊗ q_k(g) in wide limbs
              let mut inner_0 = Acc::<E::Scalar>::default();
              let mut inner_leading = Acc::<E::Scalar>::default();
              let mut inner_neg1 = Acc::<E::Scalar>::default();

              for (x_in, e_in) in poly_eq_right.iter().enumerate() {
                let id = (x_out << second_half) | x_in;

                // Get polynomial values at index id
                let (zero_a, one_a) = (&poly_A.Z[id], &poly_A.Z[id + half_p]);
                let (zero_b, one_b) = (&poly_B.Z[id], &poly_B.Z[id + half_p]);
                let (zero_c, one_c) = (&poly_C.Z[id], &poly_C.Z[id + half_p]);

                let (v0, v_leading, v_neg1) = eval_one_case_cubic_three_inputs(
                  round_idx, zero_a, one_a, zero_b, one_b, zero_c, one_c,
                );

                // Accumulate E_in * q_k in wide limbs (NO REDUCTION)
                <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                  &mut inner_0,
                  e_in,
                  &v0,
                );
                <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                  &mut inner_leading,
                  e_in,
                  &v_leading,
                );
                <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                  &mut inner_neg1,
                  e_in,
                  &v_neg1,
                );
              }

              // Phase 2: Reduce inner sums ONCE, then multiply by E_out
              let inner_0_red = <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_0);
              let inner_leading_red =
                <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_leading);
              let inner_neg1_red =
                <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&inner_neg1);

              // Accumulate E_out * inner_reduced in wide limbs (NO REDUCTION)
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut outer_acc.0,
                e_out,
                &inner_0_red,
              );
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut outer_acc.1,
                e_out,
                &inner_leading_red,
              );
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut outer_acc.2,
                e_out,
                &inner_neg1_red,
              );

              outer_acc
            },
          )
          .reduce(
            || {
              (
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
              )
            },
            |mut a, b| {
              a.0 += b.0;
              a.1 += b.1;
              a.2 += b.2;
              a
            },
          );

        // Final reduction
        (
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_0),
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_leading),
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_neg1),
        )
      } else {
        // Second half: only E_in (poly_eq_right), no E_out
        // Still use delayed reduction but simpler (single phase)
        let poly_eq_right = self.poly_eq_right_last_half();

        // Dynamic chunk size for work-stealing balance
        let min_chunk = (half_p / (rayon::current_num_threads() * 4)).max(1);
        let (acc_0, acc_leading, acc_neg1) = (0..half_p)
          .into_par_iter()
          .with_min_len(min_chunk)
          .fold(
            || {
              (
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
              )
            },
            |mut acc, id| {
              let e = &poly_eq_right[id];

              let (zero_a, one_a) = (&poly_A.Z[id], &poly_A.Z[id + half_p]);
              let (zero_b, one_b) = (&poly_B.Z[id], &poly_B.Z[id + half_p]);
              let (zero_c, one_c) = (&poly_C.Z[id], &poly_C.Z[id + half_p]);

              let (v0, v_leading, v_neg1) = eval_one_case_cubic_three_inputs(
                round_idx, zero_a, one_a, zero_b, one_b, zero_c, one_c,
              );

              // Accumulate E * q_k in wide limbs (NO REDUCTION)
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut acc.0, e, &v0,
              );
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut acc.1, e, &v_leading,
              );
              <E::Scalar as DelayedReduction<E::Scalar>>::unreduced_multiply_accumulate(
                &mut acc.2, e, &v_neg1,
              );

              acc
            },
          )
          .reduce(
            || {
              (
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
                Acc::<E::Scalar>::default(),
              )
            },
            |mut a, b| {
              a.0 += b.0;
              a.1 += b.1;
              a.2 += b.2;
              a
            },
          );

        // Final reduction
        (
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_0),
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_leading),
          <E::Scalar as DelayedReduction<E::Scalar>>::reduce(&acc_neg1),
        )
      };

      self.update_evals(&mut q0, &mut q_leading, &mut q_neg1);

      (q0, q_leading, q_neg1)
    }

    #[inline]
    pub fn bound(&mut self, r: &E::Scalar) {
      // Invariant: self.round is always >= 1 when bound is called
      // as it's initialized to 1 in new() and only incremented here
      let tau = self.taus[self.round - 1];
      self.eval_eq_left *= E::Scalar::ONE - tau - r + (*r * tau).double();
      self.round += 1;
    }

    #[inline]
    fn update_evals(
      &self,
      q0: &mut E::Scalar,
      q_leading: &mut E::Scalar,
      q_neg1: &mut E::Scalar,
    ) {
      let p = self.eval_eq_left;
      // Invariant: self.round is always >= 1 when this is called from evaluation_points methods
      let (eq_0, eq_leading, eq_neg1) = self.eq_tau_0_leading_neg1[self.round - 1];
      let eq_0_p = eq_0 * p;
      let eq_leading_p = eq_leading * p;
      let eq_neg1_p = eq_neg1 * p;

      *q0 *= eq_0_p;
      *q_leading *= eq_leading_p;
      *q_neg1 *= eq_neg1_p;
    }

    #[inline]
    fn poly_eqs_first_half(&self) -> (&Vec<E::Scalar>, &Vec<E::Scalar>, usize, usize) {
      let second_half = self.second_half;
      // Safe indexing: This method is only called when in_first_half is true,
      // which means self.round < self.first_half. Therefore self.first_half - self.round > 0
      // and the index is valid. The poly_eq_left array has first_half+1 elements (0..=first_half).
      let poly_eq_left = &self.poly_eq_left[self.first_half - self.round];
      let poly_eq_right = &self.poly_eq_right[second_half];

      debug_assert_eq!(poly_eq_right.len(), 1 << second_half);

      (
        poly_eq_left,
        poly_eq_right,
        second_half,
        (1 << second_half) - 1,
      )
    }

    #[inline]
    fn poly_eq_right_last_half(&self) -> &Vec<E::Scalar> {
      // Safe indexing: This method is only called when in_first_half is false,
      // which means self.round >= self.first_half. The maximum value of self.round
      // is init_num_vars (as we do init_num_vars rounds), so the index is always >= 0.
      &self.poly_eq_right[self.init_num_vars - self.round]
    }
  }

  /// Splits N slices in half and creates parallel zip iterators for each half.
  ///
  /// Helper function that takes an array of slices, splits each at the midpoint,
  /// and returns an array of parallel zip iterators over the left and right halves.
  ///
  /// # Type Parameters
  /// * `N` - Number of slices to split and zip
  /// * `T` - Element type (must be `Sync` for parallel iteration)
  ///
  /// # Arguments
  /// * `vec` - Array of slices to split
  /// * `half_size` - Size of each half (should equal `vec[i].len() / 2`)
  ///
  /// # Returns
  /// Array of parallel zip iterators, one for each input slice.
  #[inline]
  fn split_and_zip<const N: usize, T: Sync>(
    vec: [&[T]; N],
    half_size: usize,
  ) -> [ZipEq<Iter<'_, T>, Iter<'_, T>>; N] {
    std::array::from_fn(|i| {
      let (left, right) = vec[i].split_at(half_size);
      left.par_iter().zip_eq(right.par_iter())
    })
  }

  /// Computes BDDT evaluation points for `a*b - c`: returns (q(0), q_leading, q(-1)).
  ///
  /// q(X) = A(X)·B(X) - C(X) is degree 2, so:
  /// - q(0) = zero_a·zero_b - zero_c
  /// - q_leading = da·db (degree-2 coeff; no c term since C is degree 1)
  /// - q(-1) = (zero_a-da)·(zero_b-db) - (zero_c-dc)
  ///
  /// Saves 6 doubles + 3 adds + 2 subs per element vs eval-at-{2,3}.
  #[inline]
  fn eval_one_case_cubic_three_inputs<Scalar: PrimeField>(
    _round_idx: usize,
    zero_a: &Scalar,
    one_a: &Scalar,
    zero_b: &Scalar,
    one_b: &Scalar,
    zero_c: &Scalar,
    one_c: &Scalar,
  ) -> (Scalar, Scalar, Scalar) {
    let q0 = *zero_a * *zero_b - *zero_c;

    let da = *one_a - *zero_a;
    let db = *one_b - *zero_b;
    let dc = *one_c - *zero_c;

    // Leading coeff of A·B - C: da·db (C contributes only degree 1)
    let q_leading = da * db;

    // q(-1) = (zero_a - da)·(zero_b - db) - (zero_c - dc)
    let q_neg1 = (*zero_a - da) * (*zero_b - db) - (*zero_c - dc);

    (q0, q_leading, q_neg1)
  }
}
